import os
import json
from dotenv import load_dotenv
from openai import OpenAI

# Load environment variables from .env file
load_dotenv()

# Initialize the OpenAI client using the API key from .env
client = OpenAI(api_key=os.getenv("OPENAI_API_KEY"))

def read_test_cases(path: str) -> dict:
    """Reads the test cases to be evaluated from a JSON file."""
    with open(path, "r", encoding="utf-8") as f:
        return json.load(f)
    
def build_judge_prompt(test_case: dict) -> str:
    """Builds the instruction prompt sent to the LLM acting as judge for a single test case."""
    return f"""You are a senior QA engineer acting as an impartial judge, evaluating the quality of a single test case that was generated by another AI system.

Test case to evaluate:
{json.dumps(test_case, indent=2)}

Evaluate the test case against these 5 criteria, each scored from 1 (very poor) to 5 (excellent):

- "clarity": Is the test case written clearly and unambiguously? Could someone execute it without having to guess anything?
- "step_validity": Do the steps actually test what the title/description promise? A test case fails this if its steps don't align with what it claims to verify.
- "verifiable_expected_result": Is the expected_result something that can be objectively confirmed as true or false? Vague statements like "it works correctly" score poorly here.
- "layer_correctness": Is the layer classification (unit/integration/e2e) consistent with what the test actually does? Use these criteria:
  - "unit": tests a single function/rule in isolation, no dependency on other components or services.
  - "integration": tests interaction BETWEEN two or more components/services.
  - "e2e": tests a complete user journey from start to finish, as the end user would experience it.
- "tbd_appropriateness": When "TBD" is used, is it justified (a technical detail genuinely not determinable from a feature description alone)? Using "TBD" for information that should reasonably be specified scores poorly.

Scoring rule for "overall_verdict": if ANY criterion scores 1 or 2, the overall_verdict MUST be "fail", regardless of the other scores. It can only be "pass" if ALL criteria score 3 or higher.

Return ONLY a valid JSON object (no markdown, no code fences, no extra text) matching exactly this schema:

{{
  "test_case_id": "{test_case.get('id', 'UNKNOWN')}",
  "scores": {{
    "clarity": 1,
    "step_validity": 1,
    "verifiable_expected_result": 1,
    "layer_correctness": 1,
    "tbd_appropriateness": 1
  }},
  "overall_verdict": "pass | fail",
  "justification": "string"
}}
"""

def evaluate_test_case(test_case: dict) -> dict:
    """Sends a single test case to the LLM judge and returns the parsed evaluation."""
    prompt = build_judge_prompt(test_case)

    response = client.chat.completions.create(
        model="gpt-4o",
        messages=[
            {"role": "user", "content": prompt}
        ],
        temperature=0.2,
    )

    raw_content = response.choices[0].message.content

    try:
        return json.loads(raw_content)
    except json.JSONDecodeError as e:
        print(f"Failed to parse JSON response for test case {test_case.get('id', 'UNKNOWN')}.")
        print("Raw response was:\n", raw_content)
        raise e


def evaluate_all_test_cases(test_cases: list) -> dict:
    """Evaluates a list of test cases one by one and returns all evaluations."""
    evaluations = []

    for test_case in test_cases:
        print(f"Evaluating {test_case.get('id', 'UNKNOWN')}...")
        evaluation = evaluate_test_case(test_case)
        evaluations.append(evaluation)

    return {"evaluations": evaluations}

if __name__ == "__main__":
    test_cases_data = read_test_cases("examples/input_test_cases.json")
    test_cases = test_cases_data["test_cases"]

    results = evaluate_all_test_cases(test_cases)

    output_path = "output/evaluation_results.json"
    os.makedirs("output", exist_ok=True)
    with open(output_path, "w", encoding="utf-8") as f:
        json.dump(results, f, indent=2, ensure_ascii=False)

    print(f"Evaluation complete. Results saved to {output_path}")