"""Parses mutmut's run log and survivor list to build a simple, self-contained
HTML mutation testing report."""

import re
import os
from collections import defaultdict
from datetime import datetime, timezone

RUN_LOG_PATH = "mutation-run.log"
SURVIVORS_PATH = "mutation-survivors.txt"

# Matches lines like: "76/76  🎉 16 🫥 0  ⏰ 0  🤔 0  🙁 60  🔇 0  🧙 0"
PROGRESS_PATTERN = re.compile(r"(\d+)/(\d+)\s+🎉\s*(\d+).*?🙁\s*(\d+)")

# Matches lines like: "judge.x_evaluate_test_case__mutmut_7: survived"
SURVIVOR_PATTERN = re.compile(r"^\s*[\w.]+\.x_(\w+)__mutmut_(\d+):\s*survived\s*$")


def parse_totals():
    total = killed = survived = 0
    with open(RUN_LOG_PATH, "r", encoding="utf-8", errors="ignore") as f:
        for line in f:
            match = PROGRESS_PATTERN.search(line)
            if match:
                total = int(match.group(2))
                killed = int(match.group(3))
                survived = int(match.group(4))
    return total, killed, survived


def parse_survivors_by_function():
    grouped = defaultdict(list)
    with open(SURVIVORS_PATH, "r", encoding="utf-8", errors="ignore") as f:
        for line in f:
            match = SURVIVOR_PATTERN.match(line)
            if match:
                function_name, mutant_id = match.groups()
                grouped[function_name].append(mutant_id)
    return grouped


def build_report(total, killed, survived, grouped):
    score = round((killed / total) * 100, 1) if total else 0
    generated_at = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

    rows = ""
    for function_name, mutant_ids in sorted(grouped.items(), key=lambda x: -len(x[1])):
        rows += f"""
        <div class="fn-row">
          <span class="fn-name">{function_name}</span>
          <span class="fn-count">{len(mutant_ids)} survived</span>
        </div>
        """

    return f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>llm-as-judge - Mutation Testing Report</title>
<style>
  body {{ font-family: -apple-system, sans-serif; background: #0b0f14; color: #e6edf3; margin: 0; padding: 2rem; }}
  h1 {{ font-weight: 500; font-size: 20px; }}
  .subtitle {{ color: #8b949e; font-size: 13px; margin-top: -8px; }}
  .cards {{ display: grid; grid-template-columns: repeat(4, minmax(0, 1fr)); gap: 10px; margin: 1.5rem 0; }}
  .card {{ background: #161b22; border-radius: 10px; padding: 0.75rem 1rem; }}
  .card p:first-child {{ font-size: 12px; color: #8b949e; margin: 0 0 4px; }}
  .card p:last-child {{ font-size: 20px; font-weight: 500; margin: 0; }}
  .card.killed p:last-child {{ color: #3fb950; }}
  .card.survived p:last-child {{ color: #d29922; }}
  .fn-row {{ display: flex; justify-content: space-between; padding: 10px 14px; border: 0.5px solid #30363d; border-radius: 8px; margin-bottom: 8px; font-size: 13px; }}
  .fn-name {{ font-family: monospace; }}
  .fn-count {{ color: #d29922; }}
  .footer {{ font-size: 12px; color: #6e7681; margin-top: 1.5rem; }}
</style>
</head>
<body>
  <h1>llm-as-judge - Mutation Testing Report</h1>
  <p class="subtitle">Generated by mutmut, grouped by function</p>

  <div class="cards">
    <div class="card"><p>Total mutants</p><p>{total}</p></div>
    <div class="card killed"><p>Killed</p><p>{killed}</p></div>
    <div class="card survived"><p>Survived</p><p>{survived}</p></div>
    <div class="card"><p>Mutation score</p><p>{score}%</p></div>
  </div>

  <h3 style="font-weight: 500; font-size: 14px;">Survivors by function</h3>
  {rows}

  <p class="footer">Generated {generated_at}</p>
</body>
</html>"""


def main():
    total, killed, survived = parse_totals()
    grouped = parse_survivors_by_function()

    html = build_report(total, killed, survived, grouped)

    os.makedirs("mutation-report", exist_ok=True)
    with open("mutation-report/index.html", "w", encoding="utf-8") as f:
        f.write(html)

    print(f"Mutation report generated: {killed}/{total} killed ({survived} survived)")


if __name__ == "__main__":
    main()